version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - data:/metabase
    networks:
      mynetwork:

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      mynetwork:

volumes:
  data:
  mysql:

networks:
  mynetwork:
    ipam:
      driver: default
